apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-replicaset
  labels:
    app: tomcat-app
    type: front-end

spec:
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat-app
        type: front-end
    spec:
      containers:
        - name: tomcat-container
          image: tomcat

  replicas: 3
  selector:
    matchLabels:
      type: front-end
